version: '3.3'
services:
  downloader:
    image: tcsmr/rknd
    restart: unless-stopped
    volumes:
      - /opt/rknd/data:/app/data
    environment:
      - TELEGRAM_BOT_TOKEN=токен
      - TELEGRAM_CHAT_ID=идентификатор-чата
      - TELEGRAM_NOTIFY_ON_SUCCESS=0

